"ciflow/docker":
  globs:
    - .ci/docker/**
    - .github/workflows/docker-build.yml
  draft: false

"ciflow/docs":
  globs:
    - "*.rst"
    - "*.py"
    - Makefile
    - requirements.txt
    - _static/**
    - _templates/**
    - "*_source/**"
    - .jenkins/**
    - .github/workflows/_build-tutorials-base.yml
    - .github/workflows/build-tutorials.yml
  draft: false
