name: Bug Report
description: Create a tutorial bug report

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/pytorch/tutorials/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      **Link to the tutorial on the website:** <Add link>
    placeholder: |
      Provide a detailed description of the issue with code samples if relevant
      ```python

      # Sample code to reproduce the problem if relevant
      ```

      **Expected Result:** (Describe what you were expecting to see)


      **Actual Result:** (Describe the result)

      ```
      The error message you got, with the full traceback.
      ```

  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your environment
    description: |
      **Describe your environment:**
 
      * Platform (i.e macOS, Linux, Google Colab):
      * CUDA: 
      * PyTorch version (run `python -c "import torch; print(torch.__version__)"`):

  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
