name: 🚀 Feature request
description: Submit a proposal for a new PyTorch tutorial or improvement of an existing tutorial
title: "💡 [REQUEST] - <title>"
labels: [
  "feature"
]

body:
- type: textarea
  attributes:
    label: 🚀 Descirbe the improvement or the new tutorial
    description: |
      **Describe the improvement**
    placeholder: |
      Explain why this improvement or new tutorial is important. For example, *"This tutorial will help users to better understand feature X of PyTorch."* If there is a tutorial that you propose to replace, add here. If this is related to another GitHub issue, add a link here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Existing tutorials on this topic
    description: | 
      **Add a list of existing tutorials on the same topic.**
    placeholder: |
      List tutorials that already explain this functionality if exist. On pytorch.org or elsewhere.
      * Link
      * Link
- type: textarea
  attributes:
    label: Additional context
    description: |
      **Add additional context**
    placeholder: |
      Add any other context or screenshots about the feature request.
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
